export const BOOKING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SERVICE_COMPLETED: 'SERVICE_COMPLETED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  DISPUTED: 'DISPUTED'
});

export const ALL_BOOKING_STATUSES = Object.values(BOOKING_STATUS);

// Map of allowed status transitions
export const ALLOWED_TRANSITIONS = Object.freeze({
  [BOOKING_STATUS.PENDING]: [
    BOOKING_STATUS.ACCEPTED,
    BOOKING_STATUS.REJECTED,
    BOOKING_STATUS.CANCELLED
  ],
  [BOOKING_STATUS.ACCEPTED]: [
    BOOKING_STATUS.IN_PROGRESS,
    BOOKING_STATUS.CANCELLED
  ],
  [BOOKING_STATUS.IN_PROGRESS]: [
    BOOKING_STATUS.SERVICE_COMPLETED
  ],
  [BOOKING_STATUS.SERVICE_COMPLETED]: [
    BOOKING_STATUS.PAYMENT_PENDING
  ],
  [BOOKING_STATUS.PAYMENT_PENDING]: [
    BOOKING_STATUS.PAID,
    BOOKING_STATUS.DISPUTED
  ],
  [BOOKING_STATUS.DISPUTED]: [
    BOOKING_STATUS.PAID,
    BOOKING_STATUS.CANCELLED
  ],
  [BOOKING_STATUS.PAID]: [],
  [BOOKING_STATUS.CANCELLED]: [],
  [BOOKING_STATUS.REJECTED]: []
});

export const isValidTransition = (currentStatus, nextStatus) => {
  const allowed = ALLOWED_TRANSITIONS[currentStatus];
  return Boolean(allowed && allowed.includes(nextStatus));
};
