export const NOTIFICATION_TYPES = Object.freeze({
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_ACCEPTED: 'BOOKING_ACCEPTED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  SERVICE_STARTED: 'SERVICE_STARTED',
  SERVICE_COMPLETED: 'SERVICE_COMPLETED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REMINDER: 'PAYMENT_REMINDER',
  NEW_MESSAGE: 'NEW_MESSAGE',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED'
});

export const ALL_NOTIFICATION_TYPES = Object.values(NOTIFICATION_TYPES);
